---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: isale-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: isale-api
    spec:
      containers:
      - name: isale-api
        image: dunglv1984/isale-api:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: isale-api
---
apiVersion: v1
kind: Service
metadata:
  name: isale-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: isale-api
